server.port: 38080
spring:
  application:
    name: config-dmo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/demo_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Abc12332!
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration/{vendor}
    enabled: true

logging:
  level:
    com.apzda: debug
